services:
  healthcare-api:
    build: .
    container_name: healthcare-api
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin
    links:
      - mysql_db
    environment:
      - PMA_ARBITRARY=1
    ports:
      - '9000:80'